src/__tests__/ethr-did-resolver-test.js
src/ethr-did-resolver.js

This PR only uses named exports for the library
previously this lib was mixing default and named exports, which is not a good standard to follow

Use only named exports

---

src/ethr-did-resolver.js

This PR fixes https://github.com/decentralized-identity/ethr-did-resolver/issues/36.
Referencing the `networks.json` using `require` syntax allowed the tests to pass, but does not get picked up by `microbundle` during the build process.  It results in an error when this module is used as a dependency to resolve an ethr-did that specifies a network name in the identifier.  By using the `import` syntax instead, `microbundle` is able to correctly bundle the json data into the build output.

feat: import instead of require networks.json

---

package.json

This entry in the package.json file is causing some issues when using this library in a front end context like React

Remove ejs module distribution

---

README.md
src/__tests__/ethr-did-resolver-test.js
src/ethr-did-resolver.js

This adds explicit support for listing X25519 encryption keys in ethr-did documents
This extends the supported attribute values to include `X25519` key algorithm and `enc` key purpose.
(fixes #52)
A `DIDAttributeChanged` event for the identity `0xf3beac30c498d9e26865f34fcaa57dbb935b0d74` with the name
`did/pub/X25519/enc/base64` and the value of
`0x302a300506032b656e032100118557777ffb078774371a52b00fed75561dcf975e61c47553e664a617661052`
generates a `PublicKey` entry like this:
```javascript
{
id: "did:ethr:0xf3beac30c498d9e26865f34fcaa57dbb935b0d74#delegate-1",
type: "X25519KeyAgreementKey2019",
owner: "did:ethr:0xf3beac30c498d9e26865f34fcaa57dbb935b0d74",
publicKeyBase64: "MCowBQYDK2VuAyEAEYVXd3/7B4d0NxpSsA/tdVYdz5deYcR1U+ZkphdmEFI="
}
```
Some key algorithms would not fit certain …

feat: add encryption key support for ethr-did-documents

---

README.md

The DID resolver code snippet was missing new keyword to initialize the Resolver.
Proposed change:
From
const didResolver = Resolver(ethrDidResolver)
To
const didResolver = new Resolver(ethrDidResolver)

Change to include missing new keyword in DID resolver code snippet

---

doc/did-method-spec.md

See:
https://explorer.tau1.artis.network/address/0xdCa7EF03e98e0DC2B855bE647C39ABe984fcF21B/contracts
https://explorer.sigma1.artis.network/address/0xdCa7EF03e98e0DC2B855bE647C39ABe984fcF21B/contracts
Is there a way to register `ethr-network` for a network? `artis_t1` and `artis_s1` in this case.
Should there be more changes to ethr-did-resolver?

add ARTIS ERC1056 contract addresses to spec

---

README.md
doc/did-method-spec.md
src/__tests__/ethr-did-resolver-test.js
src/__tests__/networks-tests.js
src/ethr-did-resolver.js

fix: change 'owner' to 'controller' to follow W3C Spec (#75)

---

src/__tests__/ethr-did-resolver-test.js
src/ethr-did-resolver.js

- parsing through events from latest to earliest
- reverse events as json rpc returns one batch of events from earliest to latest
- see https://github.com/decentralized-identity/ethr-did-resolver/issues/86#issuecomment-699961595 for more details on the bug
Currently there is probably no failure/error as only events from one block are fetched. Even if there are multiple events in one block they'll most likely not interfere with each other.

fix: reverse events to have consistent order

---

doc/did-method-spec.md

The reference to the `#controller` key in the `authentication` section was broken.
The example DID document is now:
```json
{
"@context": [
"https://www.w3.org/ns/did/v1",
"https://identity.foundation/EcdsaSecp256k1RecoverySignature2020/lds-ecdsa-secp256k1-recovery2020-0.0.jsonld"
],
"id": "did:ethr:0x0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
"verificationMethod": [
{
"id": "did:ethr:0x0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798#controller",
"type": "EcdsaSecp256k1RecoveryMethod2020",
"controller": "did:ethr:0x0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
"blockchainAccountId": "0xb9c5714089478a327f09197987f16f9e5d936e8a@eip155:1"
},
{
"id": "did:ethr:0x0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f8179 …
```

docs: fix DID Document example for did:ethr:<publicKey> in spec

---

package-lock.json
package.json
src/__tests__/networks.integration.test.ts
src/__tests__/resolver.test.ts
src/helpers.ts
src/index.ts
src/logParser.ts
src/resolver.ts

This PR adds the ability to resolve previous versions of the DID document and also shows additional metadata.
When resolving normally, the `didDocumentMetadata` will contain extra `updated`  and `versionId` entries according to [did core spec](https://w3c.github.io/did-core/#did-document-metadata)
Now, you can also resolve previous versions using the `versionId` query string parameter in the DID url, setting it to the block number at which you would like to see the result.
> Example:
> `did:ethr:<publicKey>?versionId=<blockHeight>`
When resolving previous versions, the `didDocumentMetadata` will also contain `nextUpdate` and `nextVersionId`
fixes #119
closes #118

feat: versioning

---

src/__tests__/extended-id.test.ts
src/__tests__/networks.integration.test.ts
src/helpers.ts

fixes #122
Most of the PR is adding extra tests, the actual change is [on this line](https://github.com/decentralized-identity/ethr-did-resolver/pull/123/files#r616669845)
Background:
`interpretIdentifier()` is a helper method that is supposed to split a string into components
In case one of the components is a public key, to also compute the address.
In case the string is a DID, it should try to extract the network identifier section of it as well, and discard any query string

fix: ignore query string when interpreting identifiers

---

README.md
doc/did-method-spec.md

Update the spec to detail the changes from v4.2.0 (#121)
relates to #119, #121
also clarifies some changes from #99 about metadata.
I removed some sections of the readme that were duplicating entries from the spec.

docs: update specs regarding `versionId`

---

src/__tests__/networks.integration.test.ts
src/resolver.ts

fix: strip milliseconds from dateTime strings

---

src/__tests__/resolver.test.ts
src/resolver.ts

fix: reference /enc/ keys in `keyAgreement` section of DID doc

---

doc/did-method-spec.md
src/__tests__/networks.integration.test.ts
src/__tests__/resolver.test.ts
src/helpers.ts
src/resolver.ts

fixes #140
BREAKING CHANGE: some applications may expect a 0x prefix so this is a breaking change.

fix: remove 0x prefix from publicKeyHex

---

package.json
src/__tests__/networks.integration.test.ts
src/__tests__/resolver.test.ts
src/__tests__/testUtils.ts
src/resolver.ts
yarn.lock

Aurora (and maybe some other EVM chains) fail to return event logs if `fromBlock` and `toBlock` are the same. This PR fixes that by substracting `1` from `fromBlock`

fix: Getting event logs on Aurora

---

package.json
src/__tests__/networks.integration.test.ts
src/__tests__/resolver.test.ts
src/configuration.ts
src/helpers.ts
src/resolver.ts
src/third.party.types.d.ts
yarn.lock

This PR contains 2 changes:
* revert the tweaks that were necessary on aurora. They are now EVM compatible so the tweaks are no longer necessary.
* The integration test with aurora had to be updated to fit their new block history.
* This also fixes the failing builds that we've been experiencing for a couple weeks
* use the known deployments array (from ethr-did-registry) in the configuration.

fix: revert aurora tweaks and use known deployments in config

---

src/__tests__/networks.integration.test.ts
src/__tests__/resolver.test.ts
src/controller.ts

While testing the implementation of signed methods from this resolver i noticed that function `createSetAttributeHash` always encodes the `attributeValue` to uft8. 
If the controller now tries to add another key to a did, this key in hex format is also encoded to utf8. This effectively breaks the ability to add hex values via the `setAttributeSigned` method as the contract now calculates a different hash. Leading to a tx failure.

fix: hex values getting wrongly encoded to utf8 for setAttributeSigned

---

src/controller.ts

We faced issues executing transactions, because they had weird gas parameters set. We found out that it is currently hardcoded. This PR re-enables ethers to automatically determine gas price & limit as it is the default behaviour if it's not set.

chore: remove static overrides for gas price & limit

---

doc/did-method-spec.md

fixes #177
BREAKING CHANGE: This is a breaking change of the spec as "soft deletion" of non-updated DIDs is no longer considered valid.
I also took the opportunity to remove the references to deprecated ethereum testnets and to reformat the markdown.

fix(spec): remove ambiguity around deletion

---

src/__tests__/resolve.attribute.test.ts
src/controller.ts
src/helpers.ts
src/resolver.ts

fixes #184
This is technically a breaking change, since the keys in the `verificationMethod` array are no longer all referenced in the `assertionMethod`.

feat: track signing keys independently

---

src/__tests__/networks.integration.test.ts
src/config/deployments.ts
src/configuration.ts

define the Sepolia deployment of the registry contract

feat: add Sepolia deployment

---

src/__tests__/resolve.attribute.test.ts
src/controller.ts

**Overview**
When invoking `createSetAttributeHash` the present implementation checks for a hex encoded key or for a utf8 type and will encode the `attrValue` accordingly. The behaviour between `createSetAttributeHash` and `createRevokeAttributeHash` should be consistent, however, the case of the former there is no check on the `attrValue` type. This results in a `bad_signature` error in the case where a hex encoded `attrValue` is provided.
**Fix**
The proposed changes perform the same check on the `attrValue` in the `createRevokeAttributeHash` as is performed in the `createSetAttributeHash` making them consistent.

Consistent Encoding of `attrValue` on `createRevokeAttributeHash` (in line with `createSetAttributeHash`)

---

src/__tests__/config.test.ts
src/__tests__/networks.integration.test.ts
src/config/deployments.ts
src/configuration.ts

removes the test that tries to resolve on goerli

fix(test): remove the connection test for goerli network
